AWSTemplateFormatVersion: '2010-09-09'

Description: Infraestrutura automatizada com CloudFormation

Resources:

  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir SSH

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref WebSecurityGroup
      ImageId: ami-1234567890abcdef0
